"use client";

import { useState } from "react";
import "./globals.css";
import {
  HiUser,
  HiAcademicCap,
  HiLightBulb,
  HiBriefcase,
  HiCode,
  HiMail,
  HiMenu,
  HiX,
} from "react-icons/hi";

export default function Layout({ children }: { children: React.ReactNode }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <html lang="es">
      <body className="bg-gray-50">
        <nav className="fixed top-0 left-0 w-full bg-gradient-to-r from-gray-900 to-black text-white px-6 md:px-8 py-4 flex justify-between items-center z-50 shadow-lg">
          {/* Logo */}
          <div className="text-xl font-light tracking-wide">
            Portafolio Electrónico
          </div>

          {/* Botón Hamburguesa (visible en móviles) */}
          <button
            className="md:hidden text-2xl"
            onClick={() => setIsOpen(!isOpen)}
          >
            {isOpen ? <HiX /> : <HiMenu />}
          </button>

          {/* Menú de navegación */}
          <div
            className={`absolute md:static top-16 left-0 w-full md:w-auto bg-gray-900 md:bg-transparent p-4 md:p-0 space-y-4 md:space-y-0 flex flex-col md:flex-row items-center gap-6 text-lg font-light transition-all duration-300 ${
              isOpen ? "block" : "hidden md:flex"
            }`}
          >
            <a
              href="#about"
              className="flex items-center gap-2 hover:text-gray-300 transition duration-300"
            >
              <HiUser /> Sobre Mí
            </a>
            <a
              href="#formation"
              className="flex items-center gap-2 hover:text-gray-300 transition duration-300"
            >
              <HiAcademicCap /> Formación
            </a>
            <a
              href="#skills"
              className="flex items-center gap-2 hover:text-gray-300 transition duration-300"
            >
              <HiLightBulb /> Habilidades
            </a>
            <a
              href="#experience"
              className="flex items-center gap-2 hover:text-gray-300 transition duration-300"
            >
              <HiBriefcase /> Experiencia
            </a>
            <a
              href="#projects"
              className="flex items-center gap-2 hover:text-gray-300 transition duration-300"
            >
              <HiCode /> Proyectos
            </a>
            <a
              href="#contact"
              className="flex items-center gap-2 hover:text-gray-300 transition duration-300"
            >
              <HiMail /> Contacto
            </a>
          </div>
        </nav>

        {/* Espaciado para evitar que el contenido quede oculto debajo del navbar */}
        <main className="mt-16">{children}</main>
      </body>
    </html>
  );
}


/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/
