
import "./globals.css";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className="bg-gray-50">
        <nav className="fixed top-0 left-0 w-full p-4 bg-purple-700 text-white flex justify-center gap-6">
          <a href="#about" className="hover:underline">Sobre Mí</a>
          <a href="#formation" className="hover:underline">Formacion</a>
          <a href="#skills" className="hover:underline">Habilidades</a>
          <a href="#experience" className="hover:underline">Experiencia</a>
          <a href="#projects" className="hover:underline">Proyectos</a>
          <a href="#contact" className="hover:underline">Contacto</a>
          
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}


/*import Link from 'next/link';
import './globals.css';


export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className="bg-gray-50">
        <nav className="p-4 bg-purple-700 text-white">
          <div className="flex justify-around">
           
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}


/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/
